# Generated by Django 4.2.9 on 2024-01-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=200)),
                ('esubtitle', models.CharField(blank=True, max_length=200)),
                ('category', models.IntegerField(choices=[('school or work: no school, holiday, meeting..', 0), ('class: math, bookclub, korean..', 1), ('EC: music, art, sports, volunteer..', 2), ('clinic', 3), ('social: party..', 4), ('todo', 5), ('etc', 6)], default=5)),
                ('eday', models.IntegerField(choices=[('Sunday', 0), ('Monday', 1), ('Tuesday', 2), ('Wednesday', 3), ('Thursday', 4), ('Friday', 5), ('Saturday', 6)], default=0)),
                ('etime', models.CharField(blank=True, max_length=200)),
                ('ehours', models.CharField(blank=True, max_length=10)),
                ('eprice', models.IntegerField(default=0)),
                ('memo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('nickname', models.CharField(blank=True, choices=[('엄마', '엄마'), ('아빠', '아빠'), ('첫째', '첫째'), ('둘째', '둘째')], max_length=100)),
                ('history', models.CharField(blank=True, max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitle', models.CharField(max_length=200)),
                ('ssubtitle', models.CharField(blank=True, max_length=200)),
                ('sday', models.IntegerField(choices=[('Sunday', 0), ('Monday', 1), ('Tuesday', 2), ('Wednesday', 3), ('Thursday', 4), ('Friday', 5), ('Saturday', 6)], default=0)),
                ('stime', models.CharField(blank=True, max_length=200)),
                ('shours', models.CharField(blank=True, max_length=10)),
                ('sprice', models.IntegerField(default=0)),
                ('volunteerhours', models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0)),
                ('bigevent', models.IntegerField(choices=[('NO', 0), ('YES', 1)], default=0)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('eventid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='personid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.person'),
        ),
    ]
