# Generated by Django 4.2.9 on 2024-01-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bigevent',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
    ]
