# Generated by Django 4.2.9 on 2024-01-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_bigevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.IntegerField(choices=[(0, 'school or work: no school, holiday, meeting..'), (1, 'class: math, bookclub, korean..'), (2, 'EC: music, art, sports, volunteer..'), (3, 'clinic'), (4, 'social: party..'), (5, 'todo'), (6, 'etc')], default=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='eday',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sday',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='volunteerhours',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
