# Generated by Django 4.2.9 on 2024-01-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_event_category_alter_event_eday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.CharField(blank=True, choices=[(9, '9am'), (10, '10am')], max_length=200),
        ),
    ]
