# Generated by Django 4.2.9 on 2024-01-08 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_event_etime'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='stime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='volunteerhours',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
