# Generated by Django 4.2.9 on 2024-01-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_schedule_modified_alter_event_ehours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ehours',
            new_name='eduration',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='shours',
            new_name='sduration',
        ),
    ]
