# Generated by Django 4.2.9 on 2024-01-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_rename_ehours_event_eduration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eduration',
            field=models.CharField(default='60', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sduration',
            field=models.CharField(default='60', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='stime',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
    ]
