# Generated by Django 4.2.9 on 2024-01-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedule_updated_alter_schedule_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='esubtitle',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='ssubtitle',
        ),
    ]
