# Generated by Django 4.2.9 on 2024-01-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_event_esubtitle_remove_schedule_ssubtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='memo',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='history',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='memo',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='memo',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
