# Generated by Django 4.2.9 on 2024-01-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_rename_eday_event_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default='2024-01-09 00:00'),
        ),
    ]
