# Generated by Django 4.2.9 on 2024-01-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
    ]
