# Generated by Django 4.2.9 on 2024-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_remove_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='used',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
