# Generated by Django 4.2.9 on 2024-01-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_event_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='used',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
