# Generated by Django 4.2.9 on 2024-01-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_event_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='used',
            new_name='active',
        ),
    ]
