# Generated by Django 4.2.9 on 2024-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_rename_used_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='started',
            field=models.DateField(blank=True, default='2024-01-01'),
        ),
    ]
