# Generated by Django 4.2.9 on 2024-01-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_event_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bigevent',
            field=models.BooleanField(default=0),
        ),
    ]
