# Generated by Django 4.2.9 on 2024-01-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_alter_schedule_bigevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
