# Generated by Django 4.2.9 on 2024-01-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_alter_event_startdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='personid',
            field=models.IntegerField(null=True),
        ),
    ]
