# Generated by Django 4.2.9 on 2024-01-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_alter_schedule_options_schedule_personid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='personid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.person'),
        ),
    ]
