# Generated by Django 4.2.9 on 2024-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_alter_schedule_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dateday',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='datetime',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.CharField(default='60', help_text='분 단위로 입력해 주세요!', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(help_text='ex) S_piano  이름의 첫 알파벳과 함께 만들어 주세요!', max_length=200),
        ),
    ]
