# Generated by Django 4.2.9 on 2024-01-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_schedule_dateday_schedule_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='dateday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='datetime',
        ),
    ]
