# Generated by Django 4.2.9 on 2024-01-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_alter_event_enddate_alter_event_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
